const express = require('express');
const route = express.Router();
const {addEmployee,employeeList, userDetails, updateEmployeeProfile, LoadProfileData} = require('../controllers/employee.controller');
const tokenChecker = require('../middleware/tokenChecker');
const { filterEmployee } = require('../controllers/filter.controller');
route.post('/add-employee/',tokenChecker,addEmployee);
route.get('/list-employee/',tokenChecker,employeeList);
route.get('/user-details/',tokenChecker,userDetails);
route.get('/load-profile/',tokenChecker,LoadProfileData);
route.post('/update-profile/',tokenChecker,updateEmployeeProfile);
route.get('/filter/',tokenChecker,filterEmployee);
module.exports = route;